name: "FibBot"
description: "prints first and second arguments passed to fibbot"

inputs:

  enable_fib:
    description: "defines whether fibbot is enabled or not"
    required: true
    default: false

  max_threshold:
    description: "defines the max number fibbot will compute"
    required: true
    default: "100"

    pr_number:
      description: "The number of the pull request"
      required: true

    githun_token:
      description: "GitHub token to interact with GitHub API"
      required: true

# outputs:
#   results:
#     description: "prints output to logs"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}

    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
       # ./target/release/fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash
