name: "Run FibBot Action"
on: [pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run FibBot
        uses: ./
        with:
          enable_fib: "true"
          max_threshold: "500"
  
