name: "Run FibBot Action"

on:
  pull_request:
    types: [opened, synchronize, reopened] 

permissions:
  pull-requests: write
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test
        
      - name: Run FibBot
        id: result
        uses: t-desmond/fibbot@main
        with:
          enable_fib: true
          max_threshold: '10'
        env:
          pr_number: ${{ github.event.pull_request.number }}  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
