name: "run fibbot action"

on:
  push:
    branches:
      - main

jobs:
  test-fibbot-action:
  
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: print hello
        uses: actions/fibbot@v1
      
