name: "Run FibBot Action"
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Run FibBot
        id: result
        uses: ./
        with:
          enable_fib: true
          max_threshold: '100'

      # - name: display output
      #   run: echo "The inputs are ${{ steps.result.outputs.enable_fib }} and ${{ steps.result.outputs.max_threshold }}"
