name: "Run FibBot Action"
on: [push]

permissions:
  pull-requests: write
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: get pr number
        run: |
          echo "pr number: ${{ github.event.pull_request.number }}"
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Run FibBot
        id: result
        uses: ./
        with:
          enable_fib: true
          max_threshold: '100'
        env:
          pr_number: ${{ github.event.pull_request.number }}
          githun_token: ${{ secrets.GITHUB_TOKEN }}