name: "Run FibBot Action"

on:
  pull_request:
    types: [opened, synchronize, reopened] 

permissions:
  pull-requests: write
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get PR number
        run: |
          if [[ -n "${{ github.event.pull_request }}" ]]; then
            echo "PR Number: ${{ github.event.pull_request.number }}"
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "No pr found."
          fi
          
      - name: Run FibBot
        id: result
        uses: t-desmond/fibbot@main
        with:
          enable_fib: true
          max_threshold: '100'
        env:
          pr_number: ${{ env.pr_number }}  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
